window.MOTION_LOCALE = {
  font: 'NotoTC',
  language: 'zh-Hant',
  strings: {
    'CAMPUS, IN SYNC': '校園生活，與你同步',
    'NTHU · TAIWAN': '清華大學 · 臺灣',
    'YOUR CAMPUS. REIMAGINED.': '校園生活，重新想像',
    'LESS': '選課',
    'FRICTION.': '更簡單。',
    'Find your course.': '找到喜歡的課。',
    'Find your rhythm.': '排出自己的節奏。',
    'DISCOVER': '發現精彩',
    'MORE': '探索',
    'POSSIBILITY.': '更多可能。',
    'Find your next obsession': '探索下一個熱愛',
    'Machine Learning': '機器學習',
    'Design Thinking': '設計思考',
    'Data Structures': '資料結構',
    'COMPUTER SCIENCE': '資訊工程',
    'GENERAL EDUCATION': '通識教育',
    '3 CREDITS': '3 學分',
    'SEARCH LESS. DISCOVER MORE.': '少點搜尋，多點發現。',
    'FIND YOUR COURSE': '找到喜歡的課',
    'MAKE': '時間，',
    'TIME': '由你',
    'YOURS.': '安排。',
    'YOUR WEEK': '本週課表',
    'IN SYNC': '已同步',
    'MON': '星期一',
    'TUE': '星期二',
    'WED': '星期三',
    'THU': '星期四',
    'Machine': '機器',
    'Learning': '學習',
    'Design': '設計',
    'Thinking': '思考',
    'Data': '資料',
    'Structures': '結構',
    'Creative': '靈感',
    'break': '留白',
    'YOUR TIME': '自由時段',
    'Focus': '專注',
    'Explore': '探索',
    'Make': '動手',
    'something': '創作',
    'BUILD YOUR RHYTHM': '排出你的節奏',
    'BEYOND': '精彩',
    'THE CLASS.': '不只在課堂。',
    'AT THIS PLACE': '此處店家',
    'Feng Yun Building': '風雲樓',
    '2F': '2 樓',
    'A campus worth exploring.': '校園，值得好好探索。',
    'Places. People. Possibilities.': '遇見日常，發現更多可能。',
    'MAP DATA © OPENSTREETMAP CONTRIBUTORS': '地圖資料 © OpenStreetMap 貢獻者',
    'EXPLORE YOUR CAMPUS': '探索你的校園',
    'Your campus.': '你的校園，',
    'In sync.': '與你同步。',
    'BUILT FOR LIFE AT NTHU': '為清華生活而打造',
    'YOUR NEXT CHAPTER': '開啟你的下一章',
    'Play with sound': '播放影片與配樂',
    'Replay with sound': '重新播放',
    'Pause': '暫停'
  },
  headlineSizes: {
    'FRICTION.': 171,
    'POSSIBILITY.': 142,
    'MAKE': 169,
    'TIME': 196,
    'YOURS.': 173,
    'THE CLASS.': 143
  }
}
