export type LaundryMachineType = "washer" | "dryer";
export type LaundryGender = "male" | "female" | "mixed";

export const LAUNDRY_DORMS = {
  義齋: { zh: "義齋", en: "Dorm Yi" },
  明齋: { zh: "明齋", en: "Dorm Ming" },
  實齋: { zh: "實齋", en: "Dorm Shyr" },
  新齋: { zh: "新齋", en: "Dorm Hsin" },
  華齋: { zh: "華齋", en: "Dorm Hua" },
  禮齋: { zh: "禮齋", en: "Dorm Li" },
  誠齋: { zh: "誠齋", en: "Dorm Cheng" },
  雅齋: { zh: "雅齋", en: "Dorm Ya" },
  慧齋: { zh: "慧齋", en: "Dorm Huei" },
  靜齋: { zh: "靜齋", en: "Dorm Jing" },
  碩齋: { zh: "碩齋", en: "Dorm Shuo" },
  仁齋: { zh: "仁齋", en: "Dorm Jen" },
  清華會館: { zh: "清華會館", en: "NTHU Guest House I" },
} as const;

export const LAUNDRY_AREAS = {
  義齋: { zh: "義齋", en: "Dorm Yi", dorm: "義齋" },
  明齋: { zh: "明齋", en: "Dorm Ming", dorm: "明齋" },
  實齋男: { zh: "實齋男", en: "Dorm Shyr (Male)", dorm: "實齋" },
  實齋女: { zh: "實齋女", en: "Dorm Shyr (Female)", dorm: "實齋" },
  新齋: { zh: "新齋", en: "Dorm Hsin", dorm: "新齋" },
  華齋: { zh: "華齋", en: "Dorm Hua", dorm: "華齋" },
  禮齋: { zh: "禮齋", en: "Dorm Li", dorm: "禮齋" },
  誠齋: { zh: "誠齋", en: "Dorm Cheng", dorm: "誠齋" },
  雅齋: { zh: "雅齋", en: "Dorm Ya", dorm: "雅齋" },
  慧齋: { zh: "慧齋", en: "Dorm Huei", dorm: "慧齋" },
  靜齋: { zh: "靜齋", en: "Dorm Jing", dorm: "靜齋" },
  碩齋: { zh: "碩齋", en: "Dorm Shuo", dorm: "碩齋" },
  仁齋男: { zh: "仁齋男", en: "Dorm Jen (Male)", dorm: "仁齋" },
  仁齋女: { zh: "仁齋女", en: "Dorm Jen (Female)", dorm: "仁齋" },
  "清華會館 9F": {
    zh: "清華會館 9F",
    en: "NTHU Guest House I · 9F",
    dorm: "清華會館",
  },
  "清華會館 B1": {
    zh: "清華會館 B1",
    en: "NTHU Guest House I · B1",
    dorm: "清華會館",
  },
} as const;

export type LaundryDorm = keyof typeof LAUNDRY_DORMS;
export type LaundryArea = keyof typeof LAUNDRY_AREAS;

export interface LaundryMachine {
  mac: string;
  dorm: LaundryDorm;
  area: LaundryArea;
  slug: string;
  gender: LaundryGender;
  type: LaundryMachineType;
  number: number;
}

export const LAUNDRY_MACHINES: readonly LaundryMachine[] = [
  {
    mac: "94c96001b2d1",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b2d3",
    dorm: "清華會館",
    area: "清華會館 9F",
    slug: "tsinghua_hall",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b2d4",
    dorm: "清華會館",
    area: "清華會館 B1",
    slug: "tsinghua_hall",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b2e0",
    dorm: "明齋",
    area: "明齋",
    slug: "ming",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b2e1",
    dorm: "明齋",
    area: "明齋",
    slug: "ming",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b306",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b307",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b30c",
    dorm: "清華會館",
    area: "清華會館 9F",
    slug: "tsinghua_hall",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b30e",
    dorm: "明齋",
    area: "明齋",
    slug: "ming",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b310",
    dorm: "清華會館",
    area: "清華會館 B1",
    slug: "tsinghua_hall",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b311",
    dorm: "清華會館",
    area: "清華會館 9F",
    slug: "tsinghua_hall",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b328",
    dorm: "新齋",
    area: "新齋",
    slug: "hsin",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b349",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b352",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b354",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "washer",
    number: 6,
  },
  {
    mac: "94c96001b357",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "dryer",
    number: 4,
  },
  {
    mac: "94c96001b358",
    dorm: "新齋",
    area: "新齋",
    slug: "hsin",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b359",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b35b",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b35d",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 5,
  },
  {
    mac: "94c96001b35e",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b35f",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b366",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b367",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b369",
    dorm: "新齋",
    area: "新齋",
    slug: "hsin",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b371",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 6,
  },
  {
    mac: "94c96001b380",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "dryer",
    number: 5,
  },
  {
    mac: "94c96001b389",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 7,
  },
  {
    mac: "94c96001b38b",
    dorm: "實齋",
    area: "實齋男",
    slug: "shyr",
    gender: "male",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b38f",
    dorm: "新齋",
    area: "新齋",
    slug: "hsin",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b390",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "washer",
    number: 5,
  },
  {
    mac: "94c96001b391",
    dorm: "新齋",
    area: "新齋",
    slug: "hsin",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b392",
    dorm: "禮齋",
    area: "禮齋",
    slug: "li",
    gender: "mixed",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b393",
    dorm: "靜齋",
    area: "靜齋",
    slug: "jing",
    gender: "mixed",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b394",
    dorm: "靜齋",
    area: "靜齋",
    slug: "jing",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b395",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b396",
    dorm: "實齋",
    area: "實齋男",
    slug: "shyr",
    gender: "male",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b398",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b399",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b39e",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "dryer",
    number: 4,
  },
  {
    mac: "94c96001b39f",
    dorm: "實齋",
    area: "實齋男",
    slug: "shyr",
    gender: "male",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3a1",
    dorm: "靜齋",
    area: "靜齋",
    slug: "jing",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3a2",
    dorm: "實齋",
    area: "實齋女",
    slug: "shyr",
    gender: "female",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3a3",
    dorm: "靜齋",
    area: "靜齋",
    slug: "jing",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3a8",
    dorm: "慧齋",
    area: "慧齋",
    slug: "huei",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3a9",
    dorm: "靜齋",
    area: "靜齋",
    slug: "jing",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3aa",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "dryer",
    number: 4,
  },
  {
    mac: "94c96001b3ae",
    dorm: "實齋",
    area: "實齋女",
    slug: "shyr",
    gender: "female",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b3af",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3b0",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3b8",
    dorm: "明齋",
    area: "明齋",
    slug: "ming",
    gender: "mixed",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b3b9",
    dorm: "實齋",
    area: "實齋女",
    slug: "shyr",
    gender: "female",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3bb",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b3bc",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3bd",
    dorm: "明齋",
    area: "明齋",
    slug: "ming",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3bf",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3c0",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b3c1",
    dorm: "明齋",
    area: "明齋",
    slug: "ming",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3c2",
    dorm: "實齋",
    area: "實齋男",
    slug: "shyr",
    gender: "male",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3c3",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "dryer",
    number: 4,
  },
  {
    mac: "94c96001b3c5",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3c6",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "washer",
    number: 6,
  },
  {
    mac: "94c96001b3c7",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3c8",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3c9",
    dorm: "實齋",
    area: "實齋男",
    slug: "shyr",
    gender: "male",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3ca",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b3cb",
    dorm: "仁齋",
    area: "仁齋男",
    slug: "jen",
    gender: "male",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3cc",
    dorm: "實齋",
    area: "實齋男",
    slug: "shyr",
    gender: "male",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b3cd",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "dryer",
    number: 4,
  },
  {
    mac: "94c96001b3ce",
    dorm: "實齋",
    area: "實齋男",
    slug: "shyr",
    gender: "male",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3d0",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3d1",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3d2",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b3d3",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3d4",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "washer",
    number: 7,
  },
  {
    mac: "94c96001b3d5",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "dryer",
    number: 3,
  },
  {
    mac: "94c96001b3d6",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "dryer",
    number: 4,
  },
  {
    mac: "94c96001b3d7",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "washer",
    number: 5,
  },
  {
    mac: "94c96001b3d8",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "washer",
    number: 5,
  },
  {
    mac: "94c96001b3d9",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3da",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b3dc",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "washer",
    number: 6,
  },
  {
    mac: "94c96001b3dd",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b3df",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3e0",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "washer",
    number: 8,
  },
  {
    mac: "94c96001b3e1",
    dorm: "實齋",
    area: "實齋女",
    slug: "shyr",
    gender: "female",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3e2",
    dorm: "義齋",
    area: "義齋",
    slug: "yi",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3e3",
    dorm: "仁齋",
    area: "仁齋男",
    slug: "jen",
    gender: "male",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3e4",
    dorm: "華齋",
    area: "華齋",
    slug: "hua",
    gender: "mixed",
    type: "dryer",
    number: 5,
  },
  {
    mac: "94c96001b3e6",
    dorm: "慧齋",
    area: "慧齋",
    slug: "huei",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3e7",
    dorm: "慧齋",
    area: "慧齋",
    slug: "huei",
    gender: "mixed",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3e8",
    dorm: "靜齋",
    area: "靜齋",
    slug: "jing",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3e9",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3ea",
    dorm: "慧齋",
    area: "慧齋",
    slug: "huei",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3eb",
    dorm: "雅齋",
    area: "雅齋",
    slug: "ya",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3ec",
    dorm: "慧齋",
    area: "慧齋",
    slug: "huei",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3ed",
    dorm: "仁齋",
    area: "仁齋女",
    slug: "jen",
    gender: "female",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3ee",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3ef",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3f0",
    dorm: "仁齋",
    area: "仁齋女",
    slug: "jen",
    gender: "female",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3f1",
    dorm: "仁齋",
    area: "仁齋女",
    slug: "jen",
    gender: "female",
    type: "dryer",
    number: 1,
  },
  {
    mac: "94c96001b3f2",
    dorm: "仁齋",
    area: "仁齋女",
    slug: "jen",
    gender: "female",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3f3",
    dorm: "仁齋",
    area: "仁齋女",
    slug: "jen",
    gender: "female",
    type: "washer",
    number: 1,
  },
  {
    mac: "94c96001b3f4",
    dorm: "仁齋",
    area: "仁齋男",
    slug: "jen",
    gender: "male",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3f5",
    dorm: "仁齋",
    area: "仁齋男",
    slug: "jen",
    gender: "male",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b3f6",
    dorm: "仁齋",
    area: "仁齋男",
    slug: "jen",
    gender: "male",
    type: "washer",
    number: 3,
  },
  {
    mac: "94c96001b3fc",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b3fd",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "washer",
    number: 5,
  },
  {
    mac: "94c96001b3fe",
    dorm: "誠齋",
    area: "誠齋",
    slug: "cheng",
    gender: "mixed",
    type: "washer",
    number: 2,
  },
  {
    mac: "94c96001b3ff",
    dorm: "碩齋",
    area: "碩齋",
    slug: "shuo",
    gender: "mixed",
    type: "washer",
    number: 4,
  },
  {
    mac: "94c96001b400",
    dorm: "仁齋",
    area: "仁齋男",
    slug: "jen",
    gender: "male",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b43d",
    dorm: "實齋",
    area: "實齋女",
    slug: "shyr",
    gender: "female",
    type: "dryer",
    number: 2,
  },
  {
    mac: "94c96001b43e",
    dorm: "實齋",
    area: "實齋女",
    slug: "shyr",
    gender: "female",
    type: "washer",
    number: 1,
  },
];

export const LAUNDRY_MACHINES_BY_AREA = Object.fromEntries(
  (Object.keys(LAUNDRY_AREAS) as LaundryArea[]).map((area) => [
    area,
    LAUNDRY_MACHINES.filter((machine) => machine.area === area),
  ]),
) as unknown as Record<LaundryArea, readonly LaundryMachine[]>;
